import Head from 'next/head';
import {
  useEffect,
  useState,
} from 'react';
import styles from '../styles/Home.module.css';

const useDynamic = (name: string) => {
  const [value, setValue] = useState(() => () => null);

  useEffect(
    () => {
      (async () => {
        if (typeof window !== 'undefined') {
          const { default: it } = await import('remote/RepoChart');

          setValue(() => it);
        }
      })();
    },
    [name],
  );

  return value;
};

const Home = () => {
  const RepoChart = useDynamic('remote/RepoChart');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <RepoChart />
      </main>
    </>
  );
};
export default Home;
